
[build]
  base = "frontend"  # Spune Netlify să caute în folderul `frontend`
  command = "npm run build"
  publish = "dist"  # Calea către build-ul generat
  

[build.environment]
  NODE_VERSION = "22"

## API proxy către backend (ajută când folosiți rute relative)
[[redirects]]
  from = "/api/*"
  to = "https://hobbiz-mui.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/uploads/*"
  to = "https://hobbiz-mui.onrender.com/uploads/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200