# Root-level Netlify config so Netlify picks it up automatically
[build]
  base = "frontend"
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
