# Root-level Netlify config so Netlify picks it up automatically
[build]
  base = "frontend"
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  # Set BACKEND_URL in site settings for API proxy, e.g. https://your-backend.onrender.com

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
