import React, { useState, useEffect } from 'react';
import { ThemedView } from '@/components/themed-view';
import { ThemedText } from '@/components/themed-text';
import { StyleSheet, ScrollView, View, TouchableOpacity, Linking, Platform } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useAppTheme } from '@/src/context/ThemeContext';
import { Ionicons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import storage from '../../src/services/storage';
import { useLocale } from '../../src/context/LocaleContext';
import { normalizeLocale } from '../../src/i18n';
import { LinearGradient } from 'expo-linear-gradient';

// App palette per user request
const WEB_PRIMARY = '#100e9aff';
const WEB_ACCENT = '#fcc22eff';
const WEB_ACCENT_GRAD_TO = '#fcc22eff';
const WEB_BORDER_LIGHT = '#ffffff';
const WEB_TEXT_DARK = '#100e9aff';
const WEB_TEXT_BODY = '#64748b';

export default function PrivacyScreen() {
  const { tokens } = useAppTheme();
  const insets = useSafeAreaInsets();
  const router = useRouter();
  const isDark = tokens.colors.bg === '#121212';
  const { locale } = useLocale();
  const normalizedLocale = normalizeLocale(locale);
  const isEn = normalizedLocale === 'en';
  const isEs = normalizedLocale === 'es';

  const openMail = (addr: string) => Linking.openURL(`mailto:${addr}`);

  const Bullet = ({ children }: { children: React.ReactNode }) => (
    <View style={styles.bulletRow}>
      <ThemedText style={[styles.bulletSymbol, { color: tokens.colors.primary }]}>→</ThemedText>
      <ThemedText style={[styles.paragraph, styles.bulletText, { color: isDark ? '#ffffff' : '#4a5568' }]}>{children}</ThemedText>
    </View>
  );

  const SectionCard = ({ title, children }: { title: string; children: React.ReactNode }) => (
    <View style={[styles.sectionCard, { backgroundColor: tokens.colors.surface, borderColor: tokens.colors.border }]}>      
      <LinearGradient colors={[tokens.colors.primary, isDark ? '#f5186644' : WEB_ACCENT]} start={{ x: 0, y: 0 }} end={{ x: 1, y: 0 }} style={styles.sectionGradient} />
      <ThemedText style={[styles.sectionHeading, { color: isDark ? '#ffffff' : WEB_PRIMARY }]}>{title}</ThemedText>
      {children}
    </View>
  );

  return (
    <ThemedView style={[styles.container, { backgroundColor: tokens.colors.bg }]}>      
      <ScrollView style={Platform.OS === 'web' ? ({ height: '100vh' } as any) : { flex: 1 }} contentContainerStyle={styles.scroll} showsVerticalScrollIndicator={false}>
        {/* Top header with back */}
        <View style={styles.headerRow}>
          <TouchableOpacity onPress={() => router.back()} style={[styles.backButton, { backgroundColor: tokens.colors.surface }]} activeOpacity={0.8}>
            <Ionicons name="arrow-back" size={20} color={tokens.colors.text} />
          </TouchableOpacity>
          <ThemedText style={[styles.title, { color: tokens.colors.text }]}>{isEn ? 'Privacy Policy' : isEs ? 'Politica de privacidad' : 'Politica de confidențialitate'}</ThemedText>
        </View>

        {/* Hero Card */}
        <View style={[styles.heroCard, { backgroundColor: isDark ? `${WEB_PRIMARY}22` : WEB_PRIMARY }]}>          
          <View style={styles.heroOverlay} />
            <ThemedText style={[styles.heroIcon, { color: isDark ? tokens.colors.primary : '#fff' }]}>🛡️</ThemedText>
            <ThemedText style={[styles.heroTitle, { color: '#fff' }]}>{isEn ? 'Privacy Policy' : isEs ? 'Politica de privacidad' : 'Politica de confidențialitate'}</ThemedText>
            <ThemedText style={[styles.heroDate, { color: '#fff' }]}>{isEn ? 'Last updated: December 13, 2025' : isEs ? 'Ultima actualizacion: 13 de diciembre de 2025' : 'Ultima actualizare: 13 decembrie 2025'}</ThemedText>
        </View>

        {/* Intro / Transparency Box */}
        <View style={[styles.introBox, { backgroundColor: isDark ? '#282828' : WEB_ACCENT, borderColor: isDark ? 'rgba(245,24,102,0.3)' : WEB_ACCENT }]}>          
          <ThemedText style={[styles.introIcon, { color: isDark ? tokens.colors.primary : '#2c5f7a' }]}>ℹ️</ThemedText>
          <View style={styles.introContent}>            
            <ThemedText style={[styles.introStrong, { color: isDark ? '#fff' : '#2c5f7a' }]}>{isEn ? 'Transparency and Data Protection' : isEs ? 'Transparencia y proteccion de datos' : 'Transparență și protecție a datelor'}</ThemedText>
              <ThemedText style={[styles.paragraph, { color: isDark ? '#fff' : '#2c5f7a' }]}>{isEn ? 'At Hobbiz we consider the protection of personal data a core responsibility. This document describes our information handling practices in detail, in accordance with the EU General Data Protection Regulation (GDPR) and applicable Romanian law.' : isEs ? 'En Hobbiz consideramos la proteccion de datos personales una responsabilidad central. Este documento describe en detalle nuestras practicas de gestion de informacion, de acuerdo con el Reglamento General de Proteccion de Datos (GDPR) y la ley rumana aplicable.' : 'La Hobbiz, considerăm protecția datelor personale o responsabilitate fundamentală. Acest document descrie în detaliu practicile noastre de gestionare a informațiilor, conform Regulamentului General privind Protecția Datelor (GDPR) și legislației românești aplicabile.'}</ThemedText>
          </View>
        </View>

        {/* Sections */}
        <SectionCard title={isEn ? '1. Purpose and scope' : isEs ? '1. Proposito y alcance' : '1. Scopul și domeniul de aplicare'}>
          <ThemedText style={[styles.paragraph, { color: isDark ? '#ffffff' : '#4a5568' }]}>{isEn ? 'This policy applies to all information collected through the Hobbiz platform, including the website, mobile applications (iOS and Android) and any associated interfaces. It defines the legal and operational framework for processing personal data in accordance with the EU General Data Protection Regulation (GDPR), Romanian Law 190/2018, Apple App Store Guidelines, and Google Play Store Developer Policies.' : isEs ? 'Esta politica se aplica a toda la informacion recopilada a traves de la plataforma Hobbiz, incluyendo el sitio web, aplicaciones moviles (iOS y Android) y cualquier interfaz asociada. Define el marco legal y operativo para el tratamiento de datos personales conforme al Reglamento General de Proteccion de Datos (GDPR), la Ley rumana 190/2018, Apple App Store Guidelines y Google Play Store Developer Policies.' : 'Această politică se aplică tuturor informațiilor colectate prin intermediul platformei Hobbiz, inclusiv prin website, aplicații mobile (iOS și Android) și orice alte interfețe asociate. Documentul definește cadrul legal și operațional pentru prelucrarea datelor cu caracter personal conform Regulamentului General privind Protecția Datelor (GDPR), Legii 190/2018, Apple App Store Guidelines și Google Play Store Developer Policies.'}</ThemedText>
          <ThemedText style={[styles.paragraph, { color: isDark ? '#ffffff' : '#4a5568' }]}>{isEn ? 'Hobbiz is operated by an individual based in Romania. As platform administrator, I determine the purposes and means of personal data processing. This is a free community platform - no fees are charged to users. For any questions regarding this policy, please contact: team.hobbiz@gmail.com.' : isEs ? 'Hobbiz es operada por una persona en Rumania. Como administrador de la plataforma, determino los fines y medios del tratamiento de datos personales. Esta es una plataforma comunitaria gratuita: no se cobran tarifas a los usuarios. Para cualquier duda sobre esta politica, contacta: team.hobbiz@gmail.com.' : 'Hobbiz este administrată de o persoană fizică din România. În calitate de administrator al platformei, eu determin scopurile și mijloacele prelucrării datelor personale. Aceasta este o platformă comunitară gratuită - nu se percep taxe de la utilizatori. Pentru orice nelămuriri referitoare la conținutul acestei politici, contactați: team.hobbiz@gmail.com.'}</ThemedText>
          <ThemedText style={[styles.paragraph, { color: isDark ? '#ffffff' : '#4a5568', fontStyle: 'italic' }]}>{isEn ? 'Disclaimer: This platform is provided "as is" for community purposes. While I implement reasonable security measures, I cannot guarantee absolute security. By using this app, you acknowledge and accept these limitations.' : isEs ? 'Aviso: Esta plataforma se ofrece "tal cual" con fines comunitarios. Aunque implemento medidas razonables de seguridad, no puedo garantizar seguridad absoluta. Al usar esta app, usted reconoce y acepta estas limitaciones.' : 'Disclaimer: Această platformă este oferită "așa cum este" în scopuri comunitare. Deși implementez măsuri rezonabile de securitate, nu pot garanta securitate absolută. Folosind această aplicație, recunoașteți și acceptați aceste limitări.'}</ThemedText>
        </SectionCard>

        <SectionCard title={isEn ? '2. Categories of processed data' : isEs ? '2. Categorias de datos procesados' : '2. Categorii de date prelucrate'}>
          <ThemedText style={[styles.subHeading, { color: isDark ? '#ffffff' : '#355070' }]}>{isEn ? 'Data you provide voluntarily' : isEs ? 'Datos proporcionados voluntariamente' : 'Date furnizate voluntar'}</ThemedText>
          <ThemedText style={[styles.paragraph, { color: isDark ? '#ffffff' : '#4a5568' }]}>{isEn ? 'During account creation and use of the platform I collect: first name, last name, email address, phone number (optional), location/city (optional), profile photo/avatar (optional), cover image (optional), announcements content (title, description, category, location, contact details, images), messages and communications with other users, reviews and ratings you give to others, favorite announcements (saved listings). This is a free platform - no payment information is ever collected.' : isEs ? 'Durante la creacion de cuenta y uso de la plataforma recojo: nombre, apellido, email, numero de telefono (opcional), ubicacion/ciudad (opcional), foto de perfil/avatar (opcional), imagen de portada (opcional), contenido de anuncios (titulo, descripcion, categoria, ubicacion, datos de contacto, imagenes), mensajes y comunicaciones con otros usuarios, resenas y valoraciones que das a otros, anuncios favoritos (guardados). Esta es una plataforma gratuita: nunca se recolecta informacion de pago.' : 'În procesul de creare a contului și utilizare a platformei colectez: prenume, nume, adresă de email, număr de telefon (opțional), locație/oraș (opțional), fotografie de profil/avatar (opțional), imagine copertă (opțional), conținut anunțuri (titlu, descriere, categorie, locație, detalii contact, imagini), mesaje și comunicări cu alți utilizatori, recenzii și evaluări pe care le dați altora, anunțuri favorite (salvate). Aceasta este o platformă gratuită - nu se colectează niciodată informații de plată.'}</ThemedText>
          <ThemedText style={[styles.subHeading, { color: isDark ? '#ffffff' : '#355070' }]}>{isEn ? 'Automatically collected data' : isEs ? 'Datos recopilados automaticamente' : 'Date colectate automat'}</ThemedText>
          <ThemedText style={[styles.paragraph, { color: isDark ? '#ffffff' : '#4a5568' }]}>{isEn ? 'Device information (type, OS version, unique identifiers), IP address, approximate location (based on IP or GPS with your consent), app usage data (features used, time spent, interactions), crash reports and performance analytics (including Google Analytics / Firebase Analytics), cookie and similar tracking technologies. For mobile apps: device advertising ID (can be reset in device settings), push notification tokens (if notifications are enabled) — push notifications are delivered using Firebase Cloud Messaging (FCM) and related services.' : isEs ? 'Informacion del dispositivo (tipo, version del SO, identificadores unicos), direccion IP, ubicacion aproximada (basada en IP o GPS con tu consentimiento), datos de uso de la app (funciones usadas, tiempo, interacciones), reportes de fallos y analiticas de rendimiento (incluido Google Analytics / Firebase Analytics), cookies y tecnologias de seguimiento similares. Para apps moviles: ID de publicidad del dispositivo (se puede restablecer en ajustes), tokens de notificaciones push (si estan habilitadas); las notificaciones push se entregan con Firebase Cloud Messaging (FCM) y servicios relacionados.' : 'Informații despre dispozitiv (tip, versiune OS, identificatori unici), adresă IP, localizare aproximativă (bazată pe IP sau GPS cu consimțământul dvs.), date de utilizare a aplicației (funcții folosite, timp petrecut, interacțiuni), rapoarte de erori și analize de performanță (inclusiv Google Analytics / Firebase Analytics), cookie-uri și tehnologii similare de urmărire. Pentru aplicații mobile: ID publicitar dispozitiv (poate fi resetat din setările dispozitivului), token-uri notificări push (dacă notificările sunt activate) — notificările push sunt livrate prin Firebase Cloud Messaging (FCM) și servicii conexe.'}</ThemedText>
          <ThemedText style={[styles.subHeading, { color: isDark ? '#ffffff' : '#355070' }]}>{isEn ? 'Mobile-specific permissions' : isEs ? 'Permisos especificos de la app movil' : 'Permisiuni specifice aplicației mobile'}</ThemedText>
          <ThemedText style={[styles.paragraph, { color: isDark ? '#ffffff' : '#4a5568' }]}>{isEn ? 'Camera (for taking listing photos and profile pictures), Photo library (for selecting images), Location services (for showing nearby listings and location-based search), Push notifications (for messages and updates), Storage (for caching images and offline functionality). All permissions are requested only when needed and you can revoke them anytime in device settings.' : isEs ? 'Camara (para tomar fotos de anuncios y perfil), Biblioteca de fotos (para seleccionar imagenes), Servicios de ubicacion (para mostrar anuncios cercanos y busqueda por ubicacion), Notificaciones push (para mensajes y actualizaciones), Almacenamiento (para cache de imagenes y funcion offline). Todos los permisos se solicitan solo cuando son necesarios y puedes revocarlos en cualquier momento en ajustes del dispositivo.' : 'Camera (pentru fotografierea anunțurilor și pozelor de profil), Biblioteca foto (pentru selectarea imaginilor), Servicii de localizare (pentru afișarea anunțurilor din apropiere și căutare bazată pe locație), Notificări push (pentru mesaje și actualizări), Stocare (pentru cache imagini și funcționalitate offline). Toate permisiunile sunt solicitate doar când sunt necesare și le puteți revoca oricând din setările dispozitivului.'}</ThemedText>
        </SectionCard>

        <SectionCard title={isEn ? '3. Purposes and legal bases for processing' : isEs ? '3. Finalidades y bases legales del tratamiento' : '3. Scopurile și bazele juridice ale prelucrării'}>
          <ThemedText style={[styles.subHeading, { color: isDark ? '#ffffff' : '#355070' }]}>{isEn ? 'Contract performance (Art. 6(1)(b) GDPR)' : isEs ? 'Ejecucion del contrato (Art. 6(1)(b) GDPR)' : 'Executarea contractului (Art. 6(1)(b) GDPR)'}</ThemedText>
          <ThemedText style={[styles.paragraph, { color: isDark ? '#ffffff' : '#4a5568' }]}>{isEn ? 'Creating and managing your account, enabling you to post and browse announcements, facilitating communication between users via in-app messaging, managing favorites and saved listings, providing customer support, delivering push notifications about your activity (messages, favorites, reviews, account updates). Note: This is a free service - no payment processing occurs.' : isEs ? 'Crear y gestionar tu cuenta, permitir publicar y navegar anuncios, facilitar comunicacion entre usuarios via mensajeria en la app, gestionar favoritos y anuncios guardados, brindar soporte al cliente, entregar notificaciones push sobre tu actividad (mensajes, favoritos, resenas, actualizaciones de cuenta). Nota: Es un servicio gratuito: no hay procesamiento de pagos.' : 'Crearea și gestionarea contului dumneavoastră, permiterea publicării și navigării anunțurilor, facilitarea comunicării între utilizatori prin mesagerie în aplicație, gestionarea favoritelor și anunțurilor salvate, furnizarea suportului pentru clienți, livrarea notificărilor push despre activitatea dvs. (mesaje, favorite, recenzii, actualizări cont). Notă: Acesta este un serviciu gratuit - nu are loc procesare de plăți.'}</ThemedText>
          <ThemedText style={[styles.subHeading, { color: isDark ? '#ffffff' : '#355070' }]}>{isEn ? 'Legitimate interests (Art. 6(1)(f) GDPR)' : isEs ? 'Intereses legitimos (Art. 6(1)(f) GDPR)' : 'Interese legitime (Art. 6(1)(f) GDPR)'}</ThemedText>
          <ThemedText style={[styles.paragraph, { color: isDark ? '#ffffff' : '#4a5568' }]}>{isEn ? 'Improving app features and user experience, preventing fraud, spam and abuse, analyzing usage patterns to optimize performance, developing new features, securing infrastructure and detecting security threats, displaying relevant listings based on your interests and location. We balance these interests against your rights and implement appropriate safeguards.' : isEs ? 'Mejorar funciones de la app y experiencia de usuario, prevenir fraude, spam y abuso, analizar patrones de uso para optimizar rendimiento, desarrollar nuevas funciones, asegurar infraestructura y detectar amenazas, mostrar anuncios relevantes segun intereses y ubicacion. Equilibramos estos intereses con tus derechos y aplicamos salvaguardas adecuadas.' : 'Îmbunătățirea funcțiilor aplicației și a experienței utilizatorului, prevenirea fraudelor, spam-ului și abuzurilor, analizarea modelelor de utilizare pentru optimizarea performanței, dezvoltarea de noi funcționalități, securizarea infrastructurii și detectarea amenințărilor, afișarea de anunțuri relevante bazate pe interesele și locația dvs. Echilibrăm aceste interese cu drepturile dvs. și implementăm măsuri de protecție adecvate.'}</ThemedText>
          <ThemedText style={[styles.subHeading, { color: isDark ? '#ffffff' : '#355070' }]}>{isEn ? 'Consent (Art. 6(1)(a) GDPR)' : isEs ? 'Consentimiento (Art. 6(1)(a) GDPR)' : 'Consimțământ (Art. 6(1)(a) GDPR)'}</ThemedText>
          <ThemedText style={[styles.paragraph, { color: isDark ? '#ffffff' : '#4a5568' }]}>{isEn ? 'Direct marketing communications, precise location tracking (GPS), non-essential analytics and personalization, optional features requiring special permissions. You can withdraw consent at any time through app settings or by contacting us at team.hobbiz@gmail.com without affecting the lawfulness of prior processing.' : isEs ? 'Comunicaciones de marketing directo, seguimiento preciso de ubicacion (GPS), analiticas no esenciales y personalizacion, funciones opcionales que requieren permisos especiales. Puedes retirar el consentimiento en cualquier momento desde ajustes de la app o contactando a team.hobbiz@gmail.com sin afectar la legalidad del tratamiento previo.' : 'Comunicări de marketing direct, urmărire precisă a locației (GPS), analize neesențiale și personalizare, funcții opționale care necesită permisiuni speciale. Puteți retrage consimțământul oricând prin setările aplicației sau contactându-ne la team.hobbiz@gmail.com fără a afecta legalitatea prelucrării anterioare retragerii.'}</ThemedText>
          <ThemedText style={[styles.subHeading, { color: isDark ? '#ffffff' : '#355070' }]}>{isEn ? 'Legal compliance (Art. 6(1)(c) GDPR)' : isEs ? 'Cumplimiento legal (Art. 6(1)(c) GDPR)' : 'Conformitate legală (Art. 6(1)(c) GDPR)'}</ThemedText>
          <ThemedText style={[styles.paragraph, { color: isDark ? '#ffffff' : '#4a5568' }]}>{isEn ? 'Responding to lawful requests from authorities when legally required, maintaining basic records as required by applicable law, enforcing Terms of Service when necessary to protect the platform and users. As a free community platform, there are no tax or financial compliance obligations.' : isEs ? 'Responder a solicitudes legales de autoridades cuando sea requerido, mantener registros basicos segun la ley aplicable, hacer cumplir los Terminos de Servicio cuando sea necesario para proteger la plataforma y a los usuarios. Como plataforma comunitaria gratuita, no hay obligaciones fiscales ni financieras.' : 'Răspunsul la solicitări legale din partea autorităților când este necesar legal, menținerea înregistrărilor de bază conform legii, aplicarea Termenilor de Utilizare când este necesar pentru protecția platformei și utilizatorilor. Ca platformă comunitară gratuită, nu există obligații fiscale sau de conformitate financiară.'}</ThemedText>
        </SectionCard>

        <SectionCard title={isEn ? '4. Data security and confidentiality' : isEs ? '4. Seguridad y confidencialidad de datos' : '4. Securitatea și confidențialitatea datelor'}>
          <ThemedText style={[styles.paragraph, { color: isDark ? '#ffffff' : '#4a5568' }]}>{isEn ? 'I implement reasonable technical and organizational measures to protect your personal data from unauthorized access, alteration, disclosure or destruction. These measures are designed to comply with GDPR, Apple App Store, and Google Play Store requirements. However, as platform administrator, I cannot guarantee absolute security - no internet transmission or storage system is 100% secure. You use this service at your own risk.' : isEs ? 'Implemento medidas tecnicas y organizativas razonables para proteger tus datos personales contra acceso no autorizado, alteracion, divulgacion o destruccion. Estas medidas cumplen con GDPR, Apple App Store y Google Play Store. Sin embargo, como administrador de la plataforma no puedo garantizar seguridad absoluta: ninguna transmision o almacenamiento en internet es 100% seguro. Usas este servicio bajo tu propio riesgo.' : 'Implementez măsuri tehnice și organizatorice rezonabile pentru a proteja datele dumneavoastră personale împotriva accesului neautorizat, modificării, divulgării sau distrugerii. Aceste măsuri sunt concepute pentru a respecta cerințele GDPR, Apple App Store și Google Play Store. Totuși, ca administrator al platformei, nu pot garanta securitate absolută - nicio transmisie sau sistem de stocare pe internet nu este 100% sigur. Folosiți acest serviciu pe propriul risc.'}</ThemedText>
          <Bullet>{isEn ? 'Encryption: All data transmitted between your device and our servers uses TLS 1.3 encryption. Sensitive data is encrypted at rest using AES-256 encryption.' : isEs ? 'Cifrado: Todos los datos transmitidos entre tu dispositivo y nuestros servidores usan cifrado TLS 1.3. Los datos sensibles se cifran en reposo con AES-256.' : 'Criptare: Toate datele transmise între dispozitivul dvs. și serverele noastre utilizează criptare TLS 1.3. Datele sensibile sunt criptate în repaus folosind criptare AES-256.'}</Bullet>
          <Bullet>{isEn ? 'Access controls: Strict role-based access control (RBAC) with principle of least privilege. Multi-factor authentication for administrative access.' : isEs ? 'Controles de acceso: Control estricto basado en roles (RBAC) con principio de minimo privilegio. Autenticacion multifactor para acceso administrativo.' : 'Controale de acces: Control strict al accesului bazat pe roluri (RBAC) cu principiul privilegiilor minime. Autentificare multi-factor pentru acces administrativ.'}</Bullet>
          <Bullet>{isEn ? 'Security testing: Regular penetration testing, vulnerability scanning, and security audits by independent third parties.' : isEs ? 'Pruebas de seguridad: pruebas de penetracion regulares, escaneo de vulnerabilidades y auditorias de seguridad por terceros independientes.' : 'Testări de securitate: Teste de penetrare regulate, scanare vulnerabilități și audituri de securitate de către terți independenți.'}</Bullet>
          <Bullet>{isEn ? 'Staff training: All personnel with access to personal data receive regular privacy and security training and are bound by confidentiality agreements.' : isEs ? 'Formacion del personal: todo el personal con acceso a datos personales recibe capacitacion regular en privacidad y seguridad y esta sujeto a acuerdos de confidencialidad.' : 'Instruire personal: Tot personalul cu acces la date personale primește instruire regulată privind confidențialitatea și securitatea și este obligat prin acorduri de confidențialitate.'}</Bullet>
          <Bullet>{isEn ? 'Incident response: We have established procedures for detecting, investigating and responding to security incidents, including notification to affected users and authorities as required by law.' : isEs ? 'Respuesta a incidentes: tenemos procedimientos para detectar, investigar y responder a incidentes de seguridad, incluyendo notificacion a usuarios afectados y autoridades segun la ley.' : 'Răspuns la incidente: Avem proceduri stabilite pentru detectarea, investigarea și răspunsul la incidente de securitate, inclusiv notificarea utilizatorilor afectați și autorităților conform legii.'}</Bullet>
          <Bullet>{isEn ? 'Chat messages: Messages are encrypted at rest with AES-256-CBC (unique IV per message); encryption keys are stored securely as server environment variables.' : isEs ? 'Mensajes de chat: los mensajes se cifran en reposo con AES-256-CBC (IV unico por mensaje); las claves se almacenan de forma segura como variables de entorno del servidor.' : 'Mesaje chat: Mesajele sunt criptate în repaus folosind AES-256-CBC (IV unic pentru fiecare mesaj); cheile de criptare sunt stocate în siguranță ca variabile de mediu pe server.'}</Bullet>
          <Bullet>{isEn ? 'Password reset: When you request a password reset we send a 6-digit verification code to your email via MailerSend. Codes expire after 15 minutes and are rate-limited to prevent abuse.' : isEs ? 'Restablecer contrasena: cuando solicitas un reinicio, enviamos un codigo de verificacion de 6 digitos por email via MailerSend. Los codigos vencen en 15 minutos y tienen limite de intentos para prevenir abuso.' : 'Resetare parolă: Când solicitați resetarea parolei, trimitem un cod de verificare de 6 cifre pe email prin MailerSend. Codurile expiră după 15 minute și sunt supuse limitelor de rată pentru a preveni abuzul.'}</Bullet>
        </SectionCard>

        <SectionCard title={isEn ? '5. Information security' : isEs ? '5. Seguridad de la informacion' : '5. Securitatea informațiilor tale'}>
          <ThemedText style={[styles.paragraph, { color: isDark ? '#ffffff' : '#4a5568' }]}>{isEn ? 'The infrastructure is hosted on reputable cloud providers (Render.com for backend, Cloudinary for images). I implement basic security measures including: HTTPS encryption for all communications, password hashing using bcrypt, secure authentication with JWT tokens, regular security updates and patches. While these are industry-standard practices, I am an individual operator with limited resources - enterprise-level security guarantees cannot be provided.' : isEs ? 'La infraestructura esta alojada en proveedores cloud reconocidos (Render.com para backend, Cloudinary para imagenes). Implemento medidas basicas de seguridad incluyendo: cifrado HTTPS para todas las comunicaciones, hashing de contrasenas con bcrypt, autenticacion segura con tokens JWT, actualizaciones y parches de seguridad regulares. Aunque son practicas estandar, soy un operador individual con recursos limitados: no puedo ofrecer garantias de seguridad a nivel enterprise.' : 'Infrastructura este găzduită pe furnizori cloud reputați (Render.com pentru backend, Cloudinary pentru imagini). Implementez măsuri de securitate de bază inclusiv: criptare HTTPS pentru toate comunicările, hash-uire parole folosind bcrypt, autentificare securizată cu token-uri JWT, actualizări și patch-uri de securitate regulate. Deși acestea sunt practici standard în industrie, sunt un operator individual cu resurse limitate - nu pot oferi garanții de securitate la nivel enterprise.'}</ThemedText>
          <ThemedText style={[styles.subHeading, { color: isDark ? '#ffffff' : '#355070' }]}>{isEn ? 'Data retention' : isEs ? 'Retencion de datos' : 'Retenție date'}</ThemedText>
          <ThemedText style={[styles.paragraph, { color: isDark ? '#ffffff' : '#4a5568' }]}>{isEn ? 'I retain your personal data only for as long as necessary to provide the service. Account data is retained while your account is active and for up to 30 days after account deletion to allow for recovery. Messages and announcements may be permanently deleted upon account deletion. Anonymous analytics data may be retained for improving the platform. You can request complete data deletion at any time by contacting team.hobbiz@gmail.com.' : isEs ? 'Conservo tus datos personales solo el tiempo necesario para prestar el servicio. Los datos de la cuenta se conservan mientras la cuenta este activa y hasta 30 dias despues de eliminarla para permitir recuperacion. Mensajes y anuncios pueden eliminarse permanentemente al borrar la cuenta. Los datos analiticos anonimos pueden conservarse para mejorar la plataforma. Puedes solicitar eliminacion completa en cualquier momento contactando a team.hobbiz@gmail.com.' : 'Păstrez datele dumneavoastră personale doar atât timp cât este necesar pentru furnizarea serviciului. Datele contului sunt păstrate cât timp contul este activ și până la 30 zile după ștergerea contului pentru a permite recuperarea. Mesajele și anunțurile pot fi șterse permanent la ștergerea contului. Datele analitice anonime pot fi păstrate pentru îmbunătățirea platformei. Puteți solicita ștergerea completă a datelor oricând contactând team.hobbiz@gmail.com.'}</ThemedText>
          <ThemedText style={[styles.subHeading, { color: isDark ? '#ffffff' : '#355070' }]}>{isEn ? 'User recommendations' : isEs ? 'Recomendaciones para usuarios' : 'Recomandări utilizatori'}</ThemedText>
          <Bullet>{isEn ? 'Use strong, unique passwords (minimum 8 characters with letters, numbers and symbols)' : isEs ? 'Usa contrasenas fuertes y unicas (minimo 8 caracteres con letras, numeros y simbolos)' : 'Folosiți parole puternice și unice (minimum 8 caractere cu litere, numere și simboluri)'}</Bullet>
          <Bullet>{isEn ? 'Enable two-factor authentication in Settings > Security for extra protection' : isEs ? 'Activa autenticacion de dos factores en Ajustes > Seguridad para proteccion adicional' : 'Activați autentificarea cu doi factori în Setări > Securitate pentru protecție suplimentară'}</Bullet>
          <Bullet>{isEn ? 'Avoid accessing your account on public or unsecured Wi-Fi networks' : isEs ? 'Evita acceder a tu cuenta en redes Wi-Fi publicas o no seguras' : 'Evitați accesarea contului pe rețele Wi-Fi publice sau nesecurizate'}</Bullet>
          <Bullet>{isEn ? 'Review account activity regularly and report any suspicious activity immediately' : isEs ? 'Revisa la actividad de la cuenta regularmente y reporta cualquier actividad sospechosa de inmediato' : 'Verificați periodic activitatea contului și raportați orice activitate suspectă imediat'}</Bullet>
          <Bullet>{isEn ? 'Keep your app updated to the latest version to benefit from security improvements' : isEs ? 'Mantén la app actualizada a la ultima version para beneficiarte de mejoras de seguridad' : 'Mențineți aplicația actualizată la ultima versiune pentru a beneficia de îmbunătățirile de securitate'}</Bullet>
          <ThemedText style={[styles.paragraph, { color: isDark ? '#ffffff' : '#4a5568' }]}>{isEn ? <>Report security concerns to: <ThemedText onPress={() => openMail('team.hobbiz@gmail.com')} style={[styles.link, { color: tokens.colors.primary }]}>team.hobbiz@gmail.com</ThemedText></> : isEs ? <>Reporta problemas de seguridad a: <ThemedText onPress={() => openMail('team.hobbiz@gmail.com')} style={[styles.link, { color: tokens.colors.primary }]}>team.hobbiz@gmail.com</ThemedText></> : <>Raportați probleme de securitate la: <ThemedText onPress={() => openMail('team.hobbiz@gmail.com')} style={[styles.link, { color: tokens.colors.primary }]}>team.hobbiz@gmail.com</ThemedText></>}</ThemedText>
        </SectionCard>

        <SectionCard title={isEn ? '6. User rights' : isEs ? '6. Derechos de los usuarios' : '6. Drepturile utilizatorilor'}>
          <ThemedText style={[styles.paragraph, { color: isDark ? '#ffffff' : '#4a5568' }]}>{isEn ? 'Under the GDPR and applicable Romanian law, you have the following rights regarding your personal data:' : isEs ? 'Bajo el GDPR y la ley rumana aplicable, tienes los siguientes derechos sobre tus datos personales:' : 'Conform GDPR și legislației românești aplicabile, aveți următoarele drepturi referitoare la datele dumneavoastră personale:'}</ThemedText>
          <Bullet>{isEn ? 'Right of access: Request a copy of all personal data we hold about you in a structured, commonly used format.' : isEs ? 'Derecho de acceso: Solicitar una copia de todos los datos personales que tenemos sobre ti en un formato estructurado y de uso comun.' : 'Dreptul de acces: Solicitați o copie a tuturor datelor personale pe care le deținem despre dumneavoastră într-un format structurat și utilizat în mod curent.'}</Bullet>
          <Bullet>{isEn ? 'Right to rectification: Correct any inaccurate or incomplete personal data.' : isEs ? 'Derecho de rectificacion: Corregir cualquier dato personal inexacto o incompleto.' : 'Dreptul de rectificare: Corectați orice date personale inexacte sau incomplete.'}</Bullet>
          <Bullet>{isEn ? 'Right to erasure ("right to be forgotten"): Request deletion of your data when no longer necessary for original purposes or if you withdraw consent.' : isEs ? 'Derecho de supresion ("derecho al olvido"): Solicitar la eliminacion de tus datos cuando ya no sean necesarios o si retiras el consentimiento.' : 'Dreptul la ștergere ("dreptul de a fi uitat"): Solicitați ștergerea datelor când nu mai sunt necesare pentru scopurile inițiale sau dacă vă retrageți consimțământul.'}</Bullet>
          <Bullet>{isEn ? 'Right to restriction: Request limitation of data processing in certain circumstances (e.g., while contesting accuracy).' : isEs ? 'Derecho a la limitacion: Solicitar la limitacion del tratamiento en ciertas circunstancias (por ejemplo, mientras se cuestiona la exactitud).' : 'Dreptul la restricționare: Solicitați limitarea prelucrării datelor în anumite circumstanțe (de ex., în timp ce contestați exactitatea).'}</Bullet>
          <Bullet>{isEn ? 'Right to data portability: Receive your data in a machine-readable format and transmit it to another service provider.' : isEs ? 'Derecho a la portabilidad: Recibir tus datos en formato legible por maquina y transmitirlos a otro proveedor.' : 'Dreptul la portabilitatea datelor: Primiți datele într-un format care poate fi citit automat și să le transmiteți către un alt furnizor de servicii.'}</Bullet>
          <Bullet>{isEn ? 'Right to object: Object to processing based on legitimate interests or for direct marketing purposes.' : isEs ? 'Derecho de oposicion: Oponerte al tratamiento basado en intereses legitimos o con fines de marketing directo.' : 'Dreptul de opoziție: Opuneți-vă prelucrării bazate pe interese legitime sau în scopuri de marketing direct.'}</Bullet>
          <Bullet>{isEn ? 'Right to withdraw consent: Withdraw previously given consent at any time without affecting prior lawful processing.' : isEs ? 'Derecho a retirar el consentimiento: Retirar el consentimiento otorgado en cualquier momento sin afectar el tratamiento previo.' : 'Dreptul de a retrage consimțământul: Retrageți consimțământul acordat anterior oricând, fără a afecta legalitatea prelucrării anterioare.'}</Bullet>
          <Bullet>{isEn ? 'Right to lodge a complaint: File a complaint with the Romanian National Supervisory Authority for Personal Data Processing (ANSPDCP).' : isEs ? 'Derecho a presentar una queja: Presentar una queja ante la Autoridad Nacional de Supervisión del Tratamiento de Datos Personales (ANSPDCP).' : 'Dreptul de a depune plângere: Depuneți o plângere la Autoritatea Națională de Supraveghere a Prelucrării Datelor cu Caracter Personal (ANSPDCP).'}</Bullet>
          <ThemedText style={[styles.paragraph, { color: isDark ? '#ffffff' : '#4a5568' }]}>
            {isEn ? (
              <>To exercise any of these rights, contact us at <ThemedText onPress={() => openMail('team.hobbiz@gmail.com')} style={[styles.link, { color: tokens.colors.primary }]}>team.hobbiz@gmail.com</ThemedText>. We will respond within 30 days and may request identity verification to protect your data. You can also manage many settings directly in the app under Settings &gt; Privacy &amp; Data.</>
            ) : isEs ? (
              <>Para ejercer estos derechos, contactanos en <ThemedText onPress={() => openMail('team.hobbiz@gmail.com')} style={[styles.link, { color: tokens.colors.primary }]}>team.hobbiz@gmail.com</ThemedText>. Responderemos en 30 dias y podemos solicitar verificacion de identidad para proteger tus datos. Tambien puedes gestionar ajustes en la app en Ajustes &gt; Privacidad y Datos.</>
            ) : (
              <>Pentru a exercita oricare dintre aceste drepturi, contactați-ne la <ThemedText onPress={() => openMail('team.hobbiz@gmail.com')} style={[styles.link, { color: tokens.colors.primary }]}>team.hobbiz@gmail.com</ThemedText>. Vom răspunde în termen de 30 de zile și putem solicita verificarea identității pentru a vă proteja datele. De asemenea, puteți gestiona multe setări direct în aplicație la Setări &gt; Confidențialitate și Date.</>
            )}
          </ThemedText>
        </SectionCard>

        <SectionCard title={isEn ? '7. Data sharing and third parties' : isEs ? '7. Comparticion de datos y terceros' : '7. Partajarea datelor și terți'}>
          <ThemedText style={[styles.paragraph, { color: isDark ? '#ffffff' : '#4a5568' }]}>{isEn ? 'We do not sell your personal data to third parties. We may share data only in the following circumstances:' : isEs ? 'No vendemos tus datos personales a terceros. Solo podemos compartir datos en las siguientes circunstancias:' : 'Nu vindem datele dumneavoastră personale către terți. Putem partaja datele doar în următoarele circumstanțe:'}</ThemedText>
          <ThemedText style={[styles.subHeading, { color: isDark ? '#ffffff' : '#355070' }]}>{isEn ? 'Service providers' : isEs ? 'Proveedores de servicios' : 'Furnizori de servicii'}</ThemedText>
          <ThemedText style={[styles.paragraph, { color: isDark ? '#ffffff' : '#4a5568' }]}>{isEn ? 'I use the following third-party service providers to operate the platform: Backend hosting (Render.com), Image hosting and optimization (Cloudinary), Push notification services (Firebase Cloud Messaging - FCM), Analytics (Google Analytics / Firebase Analytics), OAuth authentication (Google, Facebook). These providers may process data on my behalf. I select reputable providers, but I am not responsible for their data practices - please review their privacy policies. As a free platform, no payment processors are used.' : isEs ? 'Uso los siguientes proveedores para operar la plataforma: hosting backend (Render.com), hosting y optimizacion de imagenes (Cloudinary), servicios de notificaciones push (Firebase Cloud Messaging - FCM), analiticas (Google Analytics / Firebase Analytics), autenticacion OAuth (Google, Facebook). Estos proveedores pueden procesar datos en mi nombre. Selecciono proveedores reputados, pero no soy responsable de sus practicas de datos: revisa sus politicas de privacidad. Como plataforma gratuita, no se usan procesadores de pago.' : 'Folosesc următorii furnizori de servicii terți pentru operarea platformei: Găzduire backend (Render.com), Găzduire și optimizare imagini (Cloudinary), Servicii de notificări push (Firebase Cloud Messaging - FCM), Analiză (Google Analytics / Firebase Analytics), Autentificare OAuth (Google, Facebook). Acești furnizori pot procesa date în numele meu. Selectez furnizori reputați, dar nu sunt responsabil pentru practicile lor de date - vă rog verificați politicile lor de confidențialitate. Ca platformă gratuită, nu se folosesc procesatori de plăți.'}</ThemedText>
          <ThemedText style={[styles.subHeading, { color: isDark ? '#ffffff' : '#355070' }]}>{isEn ? 'Facebook Login data processing' : isEs ? 'Tratamiento de datos de Facebook Login' : 'Prelucrare date Facebook Login'}</ThemedText>
          <ThemedText style={[styles.paragraph, { color: isDark ? '#ffffff' : '#4a5568' }]}>{isEn ? 'When you choose to sign in with Facebook, we receive limited data from Facebook based on your Facebook privacy settings and permissions you grant. This typically includes: your public profile information (name, profile picture), email address (if you grant permission). We use this data solely to create and manage your Hobbiz account, verify your identity, and provide you with our services. We do not access or request access to your Facebook friends list, posts, or other Facebook activity beyond basic profile information.' : isEs ? 'Cuando eliges iniciar sesion con Facebook, recibimos datos limitados segun tus ajustes de privacidad y permisos. Normalmente incluye: informacion del perfil publico (nombre, foto), email (si otorgas permiso). Usamos estos datos solo para crear y gestionar tu cuenta Hobbiz, verificar identidad y brindar servicios. No accedemos ni solicitamos acceso a tu lista de amigos, publicaciones u otras actividades de Facebook mas alla de la informacion basica del perfil.' : 'Când alegeți să vă autentificați cu Facebook, primim date limitate de la Facebook în baza setărilor dvs. de confidențialitate Facebook și permisiunilor pe care le acordați. Acestea includ de obicei: informații din profilul public (nume, poză de profil), adresa de email (dacă acordați permisiunea). Folosim aceste date exclusiv pentru a crea și gestiona contul dvs. Hobbiz, pentru a vă verifica identitatea și pentru a vă furniza serviciile noastre. Nu accesăm și nu solicităm acces la lista dvs. de prieteni Facebook, postări sau alte activități Facebook dincolo de informațiile de bază ale profilului.'}</ThemedText>
          <Bullet>{isEn ? 'You control what data Facebook shares with us through your Facebook privacy settings' : isEs ? 'Controlas que datos comparte Facebook con nosotros mediante tus ajustes de privacidad' : 'Controlați ce date Facebook partajează cu noi prin setările de confidențialitate Facebook'}</Bullet>
          <Bullet>{isEn ? 'We do not post to Facebook on your behalf without explicit permission' : isEs ? 'No publicamos en Facebook en tu nombre sin permiso explicito' : 'Nu postăm pe Facebook în numele dvs. fără permisiunea dvs. explicită'}</Bullet>
          <Bullet>{isEn ? 'You can disconnect your Facebook account anytime from Settings > Account > Connected Accounts' : isEs ? 'Puedes desconectar tu cuenta de Facebook en cualquier momento en Ajustes > Cuenta > Cuentas conectadas' : 'Puteți deconecta contul Facebook oricând din Setări > Cont > Conturi Conectate'}</Bullet>
          <Bullet>{isEn ? <>Review Facebook&apos;s data policies at: <ThemedText onPress={() => Linking.openURL('https://www.facebook.com/privacy/policy')} style={[styles.link, { color: tokens.colors.primary }]}>facebook.com/privacy/policy</ThemedText></> : isEs ? <>Revisa las politicas de datos de Facebook en: <ThemedText onPress={() => Linking.openURL('https://www.facebook.com/privacy/policy')} style={[styles.link, { color: tokens.colors.primary }]}>facebook.com/privacy/policy</ThemedText></> : <>Consultați politicile de date Facebook la: <ThemedText onPress={() => Linking.openURL('https://www.facebook.com/privacy/policy')} style={[styles.link, { color: tokens.colors.primary }]}>facebook.com/privacy/policy</ThemedText></>}</Bullet>
          <ThemedText style={[styles.subHeading, { color: isDark ? '#ffffff' : '#355070' }]}>{isEn ? 'Facebook data deletion' : isEs ? 'Eliminacion de datos de Facebook' : 'Ștergerea datelor Facebook'}</ThemedText>
          <ThemedText style={[styles.paragraph, { color: isDark ? '#ffffff' : '#4a5568' }]}>{isEn ? <>When you delete your Hobbiz account, all data associated with your account (including data received from Facebook) will be permanently deleted within 30 days. You can also request immediate data deletion by visiting our Data Deletion page or contacting <ThemedText onPress={() => openMail('team.hobbiz@gmail.com')} style={[styles.link, { color: tokens.colors.primary }]}>team.hobbiz@gmail.com</ThemedText>. To revoke Hobbiz&apos;s access to your Facebook data entirely, visit Facebook Settings &gt; Apps and Websites and remove Hobbiz from the list.</> : isEs ? <>Cuando eliminas tu cuenta Hobbiz, todos los datos asociados (incluidos los recibidos de Facebook) se eliminan definitivamente en 30 dias. Tambien puedes solicitar eliminacion inmediata visitando nuestra pagina de Eliminacion de Datos o contactando a <ThemedText onPress={() => openMail('team.hobbiz@gmail.com')} style={[styles.link, { color: tokens.colors.primary }]}>team.hobbiz@gmail.com</ThemedText>. Para revocar por completo el acceso de Hobbiz a tus datos de Facebook, visita Ajustes de Facebook &gt; Apps y sitios web y elimina Hobbiz de la lista.</> : <>Când vă ștergeți contul Hobbiz, toate datele asociate contului dvs. (inclusiv datele primite de la Facebook) vor fi șterse permanent în termen de 30 de zile. Puteți solicita și ștergerea imediată a datelor accesând pagina noastră de Ștergere Date sau contactând <ThemedText onPress={() => openMail('team.hobbiz@gmail.com')} style={[styles.link, { color: tokens.colors.primary }]}>team.hobbiz@gmail.com</ThemedText>. Pentru a revoca complet accesul Hobbiz la datele dvs. Facebook, accesați Setări Facebook &gt; Aplicații și Site-uri Web și eliminați Hobbiz din listă.</>}</ThemedText>
          <ThemedText style={[styles.subHeading, { color: isDark ? '#ffffff' : '#355070' }]}>{isEn ? 'Legal requirements' : isEs ? 'Requisitos legales' : 'Cerințe legale'}</ThemedText>
          <ThemedText style={[styles.paragraph, { color: isDark ? '#ffffff' : '#4a5568' }]}>{isEn ? 'We may disclose data when required by law, court order, or governmental request, to enforce our Terms of Service, to protect our rights and safety, or to investigate fraud and security issues. We will notify you of such disclosures unless prohibited by law.' : isEs ? 'Podemos divulgar datos cuando lo exige la ley, una orden judicial o una solicitud gubernamental, para hacer cumplir los Terminos de Servicio, proteger derechos y seguridad o investigar fraude y problemas de seguridad. Te notificaremos salvo que la ley lo prohiba.' : 'Putem divulga date când este necesar prin lege, ordin judecătoresc sau solicitare guvernamentală, pentru a aplica Termenii de Utilizare, pentru a ne proteja drepturile și siguranța sau pentru a investiga fraude și probleme de securitate. Vă vom notifica despre astfel de divulgări dacă nu este interzis prin lege.'}</ThemedText>
          <ThemedText style={[styles.subHeading, { color: isDark ? '#ffffff' : '#355070' }]}>{isEn ? 'Platform transfer' : isEs ? 'Transferencia de la plataforma' : 'Transfer platformă'}</ThemedText>
          <ThemedText style={[styles.paragraph, { color: isDark ? '#ffffff' : '#4a5568' }]}>{isEn ? 'If the platform is transferred to a new administrator or entity in the future, your data may be included in the transfer. I will notify you at least 30 days in advance via email and in-app notification, and you will have the option to delete your account and all associated data before the transfer.' : isEs ? 'Si la plataforma se transfiere a un nuevo administrador o entidad en el futuro, tus datos pueden incluirse en la transferencia. Te avisare con al menos 30 dias de antelacion por email y notificacion en la app, y tendras la opcion de eliminar tu cuenta y datos antes de la transferencia.' : 'Dacă platforma este transferată către un nou administrator sau entitate în viitor, datele dumneavoastră pot fi incluse în transfer. Vă voi notifica cu cel puțin 30 zile în avans prin email și notificare în aplicație, și veți avea opțiunea de a vă șterge contul și toate datele asociate înainte de transfer.'}</ThemedText>
          <ThemedText style={[styles.subHeading, { color: isDark ? '#ffffff' : '#355070' }]}>{isEn ? 'International data transfers' : isEs ? 'Transferencias internacionales de datos' : 'Transferuri internaționale de date'}</ThemedText>
          <ThemedText style={[styles.paragraph, { color: isDark ? '#ffffff' : '#4a5568' }]}>{isEn ? 'Your data is primarily stored within the European Economic Area (EEA). Where we use service providers outside the EEA, we ensure appropriate safeguards through EU Standard Contractual Clauses or the provider\'s adequacy decision status.' : isEs ? 'Tus datos se almacenan principalmente dentro del Espacio Economico Europeo (EEE). Si usamos proveedores fuera del EEE, aseguramos salvaguardas adecuadas mediante Clausulas Contractuales Tipo de la UE o el estatus de decision de adecuacion del proveedor.' : 'Datele dumneavoastră sunt stocate în principal în Spațiul Economic European (SEE). Unde folosim furnizori de servicii din afara SEE, asigurăm garanții adecvate prin Clauze Contractuale Standard UE sau statutul de decizie de adecvare al furnizorului.'}</ThemedText>
        </SectionCard>

        <SectionCard title={isEn ? '8. Children\'s privacy' : isEs ? '8. Privacidad de los ninos' : '8. Confidențialitatea copiilor'}>
          <ThemedText style={[styles.paragraph, { color: isDark ? '#ffffff' : '#4a5568' }]}>{isEn ? 'Hobbiz is not intended for children under the age of 16. We do not knowingly collect personal data from children. If you are under 16, please do not use our app or provide any personal information. If we become aware that we have collected data from a child under 16 without parental consent, we will take immediate steps to delete that information.' : isEs ? 'Hobbiz no esta destinado a menores de 16 anos. No recopilamos datos personales de menores de forma consciente. Si tienes menos de 16 anos, no uses nuestra app ni proporciones informacion personal. Si detectamos que hemos recopilado datos de un menor sin consentimiento parental, tomaremos medidas inmediatas para eliminarlos.' : 'Hobbiz nu este destinat copiilor sub 16 ani. Nu colectăm în mod conștient date personale de la copii. Dacă aveți sub 16 ani, vă rugăm să nu folosiți aplicația noastră și să nu furnizați informații personale. Dacă aflăm că am colectat date de la un copil sub 16 ani fără consimțământul părinților, vom lua măsuri imediate pentru a șterge acele informații.'}</ThemedText>
          <ThemedText style={[styles.paragraph, { color: isDark ? '#ffffff' : '#4a5568' }]}>{isEn ? <>Parents or guardians who believe their child has provided personal data should contact us immediately at <ThemedText onPress={() => openMail('team.hobbiz@gmail.com')} style={[styles.link, { color: tokens.colors.primary }]}>team.hobbiz@gmail.com</ThemedText> so we can delete the information.</> : isEs ? <>Padres o tutores que crean que su hijo proporciono datos personales deben contactarnos de inmediato en <ThemedText onPress={() => openMail('team.hobbiz@gmail.com')} style={[styles.link, { color: tokens.colors.primary }]}>team.hobbiz@gmail.com</ThemedText> para poder eliminar la informacion.</> : <>Părinții sau tutorii care cred că copilul lor a furnizat date personale ar trebui să ne contacteze imediat la <ThemedText onPress={() => openMail('team.hobbiz@gmail.com')} style={[styles.link, { color: tokens.colors.primary }]}>team.hobbiz@gmail.com</ThemedText> pentru a putea șterge informațiile.</>}</ThemedText>
        </SectionCard>

        <SectionCard title={isEn ? '9. Changes to this policy' : isEs ? '9. Cambios en esta politica' : '9. Modificări ale acestei politici'}>
          <ThemedText style={[styles.paragraph, { color: isDark ? '#ffffff' : '#4a5568' }]}>{isEn ? 'We may update this Privacy Policy from time to time to reflect changes in our practices, technology, legal requirements or for other operational reasons. The "Last updated" date at the top of this policy indicates when it was most recently revised.' : isEs ? 'Podemos actualizar esta Politica de Privacidad de vez en cuando para reflejar cambios en practicas, tecnologia, requisitos legales u otras razones operativas. La fecha "Ultima actualizacion" indica cuando se reviso por ultima vez.' : 'Putem actualiza această Politică de Confidențialitate periodic pentru a reflecta modificările practicilor noastre, tehnologiei, cerințelor legale sau din alte motive operaționale. Data "Ultima actualizare" din partea de sus a acestei politici indică când a fost revizuită cel mai recent.'}</ThemedText>
          <ThemedText style={[styles.paragraph, { color: isDark ? '#ffffff' : '#4a5568' }]}>{isEn ? 'For material changes that significantly affect your rights, we will notify you via email and/or prominent in-app notification at least 30 days before the changes take effect. We encourage you to review this policy periodically.' : isEs ? 'Para cambios materiales que afecten significativamente tus derechos, te notificaremos por email y/o notificacion destacada en la app al menos 30 dias antes de que entren en vigor. Te animamos a revisar esta politica periodicamente.' : 'Pentru modificări materiale care afectează semnificativ drepturile dumneavoastră, vă vom notifica prin email și/sau notificare proeminentă în aplicație cu cel puțin 30 de zile înainte ca modificările să intre în vigoare. Vă încurajăm să revizuiți periodic această politică.'}</ThemedText>
          <ThemedText style={[styles.paragraph, { color: isDark ? '#ffffff' : '#4a5568' }]}>{isEn ? 'Continued use of our services after changes become effective constitutes acceptance of the updated Privacy Policy. If you do not agree with the changes, you should stop using the app and may delete your account.' : isEs ? 'El uso continuado de nuestros servicios despues de que los cambios sean efectivos constituye aceptacion de la Politica de Privacidad actualizada. Si no estas de acuerdo, deberias dejar de usar la app y puedes eliminar tu cuenta.' : 'Utilizarea continuă a serviciilor noastre după ce modificările devin efective constituie acceptarea Politicii de Confidențialitate actualizate. Dacă nu sunteți de acord cu modificările, ar trebui să încetați utilizarea aplicației și puteți să vă ștergeți contul.'}</ThemedText>
        </SectionCard>

        <SectionCard title={isEn ? '10. Contact and additional information' : isEs ? '10. Contacto e informacion adicional' : '10. Contact și informații suplimentare'}>
          <ThemedText style={[styles.paragraph, { color: isDark ? '#ffffff' : '#4a5568' }]}>{isEn ? 'For any questions, concerns or requests regarding this Privacy Policy or data practices, please contact:' : isEs ? 'Para cualquier pregunta o solicitud sobre esta Politica de Privacidad o practicas de datos, contacta:' : 'Pentru orice întrebări, nelămuriri sau solicitări referitoare la această Politică de Confidențialitate sau practicile privind datele, vă rugăm să contactați:'}</ThemedText>
          <Bullet>{isEn ? <>Platform Administrator (Data Controller): Individual based in Romania - Email: <ThemedText onPress={() => openMail('team.hobbiz@gmail.com')} style={[styles.link, { color: tokens.colors.primary }]}>team.hobbiz@gmail.com</ThemedText></> : isEs ? <>Administrador de la plataforma (Responsable de tratamiento): Persona en Rumania - Email: <ThemedText onPress={() => openMail('team.hobbiz@gmail.com')} style={[styles.link, { color: tokens.colors.primary }]}>team.hobbiz@gmail.com</ThemedText></> : <>Administrator Platformă (Operator de date): Persoană fizică din România - Email: <ThemedText onPress={() => openMail('team.hobbiz@gmail.com')} style={[styles.link, { color: tokens.colors.primary }]}>team.hobbiz@gmail.com</ThemedText></>}</Bullet>
          <Bullet>{isEn ? <>All inquiries (privacy, security, data requests): <ThemedText onPress={() => openMail('team.hobbiz@gmail.com')} style={[styles.link, { color: tokens.colors.primary }]}>team.hobbiz@gmail.com</ThemedText></> : isEs ? <>Todas las solicitudes (privacidad, seguridad, solicitudes de datos): <ThemedText onPress={() => openMail('team.hobbiz@gmail.com')} style={[styles.link, { color: tokens.colors.primary }]}>team.hobbiz@gmail.com</ThemedText></> : <>Toate solicitările (confidențialitate, securitate, cereri de date): <ThemedText onPress={() => openMail('team.hobbiz@gmail.com')} style={[styles.link, { color: tokens.colors.primary }]}>team.hobbiz@gmail.com</ThemedText></>}</Bullet>
          <ThemedText style={[styles.paragraph, { color: isDark ? '#ffffff' : '#4a5568' }]}>{isEn ? 'Romanian National Supervisory Authority for Personal Data Processing (ANSPDCP): If you believe your data protection rights have been violated, you have the right to lodge a complaint with ANSPDCP at www.dataprotection.ro' : isEs ? 'Autoridad Nacional de Supervision del Tratamiento de Datos Personales (ANSPDCP): Si consideras que se vulneraron tus derechos, puedes presentar una queja ante ANSPDCP en www.dataprotection.ro' : 'Autoritatea Națională de Supraveghere a Prelucrării Datelor cu Caracter Personal (ANSPDCP): Dacă considerați că drepturile dumneavoastră de protecție a datelor au fost încălcate, aveți dreptul de a depune o plângere la ANSPDCP la www.dataprotection.ro'}</ThemedText>
          <ThemedText style={[styles.paragraph, { color: isDark ? '#ffffff' : '#4a5568' }]}>{isEn ? 'I am committed to resolving privacy concerns promptly and transparently. I will respond to all inquiries within 30 days of receipt. However, as an individual administrator with limited resources, complex requests may take longer to process.' : isEs ? 'Me comprometo a resolver inquietudes de privacidad de forma rapida y transparente. Respondere a todas las solicitudes dentro de 30 dias desde su recepcion. Sin embargo, como administrador individual con recursos limitados, solicitudes complejas pueden tardar mas.' : 'Mă angajez să rezolv preocupările legate de confidențialitate prompt și transparent. Voi răspunde la toate solicitările în termen de 30 de zile de la primire. Totuși, ca administrator individual cu resurse limitate, solicitările complexe pot necesita mai mult timp pentru procesare.'}</ThemedText>
        </SectionCard>
      </ScrollView>
    </ThemedView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1 },
  scroll: { paddingTop: 8, paddingHorizontal: 16, paddingBottom: 48, gap: 20 },
  headerRow: { flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 4 },
  backButton: { width: 44, height: 44, borderRadius: 999, alignItems: 'center', justifyContent: 'center' },
  title: { fontSize: 22, fontWeight: '700' },
  heroCard: { padding: 40, borderRadius: 24, overflow: 'hidden', alignItems: 'center', justifyContent: 'center', shadowColor: '#000', shadowOpacity: 0.15, shadowRadius: 24, shadowOffset: { width: 0, height: 8 } },
  heroOverlay: { position: 'absolute', top: -80, right: -80, width: 300, height: 300, borderRadius: 150, backgroundColor: 'rgba(252,194,46,0.18)' },
  heroIcon: { fontSize: 48, marginBottom: 20 },
  heroTitle: { fontSize: 26, fontWeight: '700', textAlign: 'center', marginBottom: 12, letterSpacing: -0.5 },
  heroDate: { fontSize: 14, fontWeight: '500', opacity: 0.95 },
  introBox: { borderRadius: 20, padding: 28, flexDirection: 'row', gap: 20, shadowColor: '#000', shadowOpacity: 0.08, shadowRadius: 24, shadowOffset: { width: 0, height: 8 } },
  introIcon: { fontSize: 30, marginTop: 4 },
  introContent: { flex: 1 },
  introStrong: { fontSize: 18, fontWeight: '700', marginBottom: 8 },
  sectionCard: { borderRadius: 20, padding: 24, marginBottom: 10, overflow: 'hidden', position: 'relative', shadowColor: '#000', shadowOpacity: 0.08, shadowRadius: 20, shadowOffset: { width: 0, height: 6 } },
  sectionGradient: { position: 'absolute', top: 0, left: 0, height: 4, right: 0 },
  sectionHeading: { fontSize: 20, fontWeight: '700', marginBottom: 12 },
  subHeading: { fontSize: 16, fontWeight: '600', marginTop: 8, marginBottom: 6 },
  paragraph: { fontSize: 14.5, lineHeight: 22, marginBottom: 12 },
  bulletRow: { flexDirection: 'row', alignItems: 'flex-start', marginBottom: 10 },
  bulletSymbol: { fontSize: 16, marginRight: 6, lineHeight: 22, fontWeight: '700' },
  bulletText: { flex: 1, marginBottom: 0 },
  link: { textDecorationLine: 'underline' },
});
