spec:
  name: hobbiz-backend
  # DigitalOcean App Platform spec to deploy backend service
  services:
    - name: backend
      environment_slug: node-js
      source_dir: backend
      github:
        # If connecting GitHub, DO will manage; if deploying from local, this is ignored
        branch: main
        deploy_on_push: true
      build_command: npm ci
      run_command: npm start
      http_port: 5000
      instance_count: 1
      instance_size_slug: basic-xxs
      routes:
        - path: /
      health_check:
        path: /api/health
        initial_delay_seconds: 10
      envs:
        - key: NODE_ENV
          value: production
          scope: RUN_AND_BUILD_TIME
        - key: PORT
          value: "5000"
        - key: FRONTEND_URL
          value: https://hobbiz.netlify.app
        - key: MONGODB_URI
          value: ""
          type: SECRET
        - key: JWT_SECRET
          value: ""
          type: SECRET
        - key: SESSION_SECRET
          value: ""
          type: SECRET
        - key: CLOUDINARY_CLOUD_NAME
          value: ""
          type: SECRET
        - key: CLOUDINARY_API_KEY
          value: ""
          type: SECRET
        - key: CLOUDINARY_API_SECRET
          value: ""
          type: SECRET
