// Listă curată de domenii de email disposable / temporare cunoscute.
// Sursa: agregat din liste publice (disposable-email-domains pe npm, etc.)
// Sub o formă Set pentru lookup O(1).

const DISPOSABLE_DOMAINS = new Set([
  '0815.ru', '0wnd.net', '0wnd.org', '10mail.org', '10minutemail.com',
  '10minutemail.net', '20minutemail.com', '30minutemail.com', '33mail.com',
  '7tags.com', 'air2send.com', 'amilegit.com', 'anonbox.net', 'anonymail.dk',
  'anonymbox.com', 'antichef.com', 'antichef.net', 'antireg.ru', 'antispam.de',
  'baxomale.ht.cx', 'beefmilk.com', 'bigprofessor.so', 'binkmail.com',
  'bio-muesli.net', 'bobmail.info', 'bofthew.com', 'brefmail.com', 'bsnow.net',
  'bspamfree.org', 'bugmenot.com', 'bumpymail.com', 'casualdx.com',
  'centermail.com', 'chammy.info', 'cheaphub.net', 'chogmail.com',
  'clrmail.com', 'cmail.club', 'consumerriot.com', 'cool.fr.nf', 'correo.blogos.net',
  'cosmorph.com', 'courriel.fr.nf', 'courrieltemporaire.com', 'crazymailing.com',
  'curryworld.de', 'cust.in', 'dacoolest.com', 'dandikmail.com',
  'dayrep.com', 'deadaddress.com', 'deadspam.com', 'delikkt.de',
  'despam.it', 'despammed.com', 'devnullmail.com', 'dharmatel.net',
  'disposeamail.com', 'disposemail.com', 'dispostable.com', 'dodgeit.com',
  'dodgit.com', 'donemail.ru', 'dontreg.com', 'dontsendmespam.de',
  'drdrb.net', 'dump-email.info', 'dumpyemail.com', 'e4ward.com',
  'easytrashmail.com', 'einmalmail.de', 'einrot.com', 'eintagsmail.de',
  'emailgo.de', 'emailias.com', 'emailinfive.com', 'emailmiser.com',
  'emailsensei.com', 'emailtemporanea.com', 'emailtemporanea.net',
  'emailtemporario.com.br', 'emailthe.net', 'emailtmp.com', 'emailwarden.com',
  'emailx.at.hm', 'emailxfer.com', 'emeil.in', 'emeil.ir', 'emz.net',
  'enterto.com', 'ephemail.net', 'evopo.com', 'explodemail.com',
  'fakeinbox.com', 'fakeinformation.com', 'fansworldwide.de', 'fastacura.com',
  'fastchevy.com', 'fastchrysler.com', 'fastkawasaki.com', 'fastmazda.com',
  'fastmitsubishi.com', 'fastnissan.com', 'fastsubaru.com', 'fastsuzuki.com',
  'fasttoyota.com', 'fastyamaha.com', 'filzmail.com', 'fizmail.com',
  'fr33mail.info', 'frapmail.com', 'front14.org', 'fux0ringduh.com',
  'garliclife.com', 'get1mail.com', 'get2mail.fr', 'getairmail.com',
  'getmails.eu', 'getonemail.com', 'getonemail.net', 'ghosttexter.de',
  'girlsundertheinfluence.com', 'gishpuppy.com', 'gotmail.net', 'gotmail.org',
  'gotti.otherinbox.com', 'great-host.in', 'greensloth.com', 'grr.la',
  'guerillamail.biz', 'guerillamail.com', 'guerrillamail.biz',
  'guerrillamail.com', 'guerrillamail.de', 'guerrillamail.info',
  'guerrillamail.net', 'guerrillamail.org', 'guerrillamailblock.com',
  'haltospam.com', 'hatespam.org', 'hidemail.de', 'hochsitze.com',
  'hopemail.biz', 'hotpop.com', 'hulapla.de', 'iheartspam.org',
  'imails.info', 'incognitomail.com', 'incognitomail.net', 'incognitomail.org',
  'instant-mail.de', 'instantemailaddress.com', 'ipoo.org', 'irish2me.com',
  'iwi.net', 'jetable.com', 'jetable.fr.nf', 'jetable.net', 'jetable.org',
  'jnxjn.com', 'jourrapide.com', 'jsrsolutions.com', 'kasmail.com',
  'kaspop.com', 'killmail.com', 'killmail.net', 'klassmaster.com',
  'klzlk.com', 'koszmail.pl', 'kurzepost.de', 'letthemeatspam.com',
  'lhsdv.com', 'lifebyfood.com', 'link2mail.net', 'litedrop.com',
  'lol.ovpn.to', 'lopl.co.cc', 'lortemail.dk', 'lovemeleaveme.com',
  'lr78.com', 'm21.cc', 'mail-filter.com', 'mail-temporaire.fr', 'mail.by',
  'mail.mezimages.net', 'mail.zp.ua', 'mail1a.de', 'mail21.cc',
  'mail333.com', 'mail4trash.com', 'mailbidon.com', 'mailblocks.com',
  'mailbucket.org', 'mailcat.biz', 'mailcatch.com', 'maildrop.cc',
  'maileater.com', 'mailexpire.com', 'mailfa.tk', 'mailforspam.com',
  'mailfreeonline.com', 'mailguard.me', 'mailin8r.com', 'mailinater.com',
  'mailinator.com', 'mailinator.net', 'mailinator.org', 'mailinator2.com',
  'mailincubator.com', 'mailismagic.com', 'mailme.lv', 'mailme24.com',
  'mailmetrash.com', 'mailmoat.com', 'mailms.com', 'mailnator.com',
  'mailnesia.com', 'mailnull.com', 'mailpick.biz', 'mailrock.biz',
  'mailscrap.com', 'mailshell.com', 'mailsiphon.com', 'mailtemp.info',
  'mailtome.de', 'mailtothis.com', 'mailtrash.net', 'mailtv.net',
  'mailtv.tv', 'mailzilla.com', 'mailzilla.org', 'mbx.cc', 'mega.zik.dj',
  'meinspamschutz.de', 'meltmail.com', 'messagebeamer.de', 'mierdamail.com',
  'mintemail.com', 'misterpinball.de', 'mobi.web.id', 'moburl.com',
  'moncourrier.fr.nf', 'monemail.fr.nf', 'monmail.fr.nf', 'msa.minsmail.com',
  'mt2009.com', 'mt2014.com', 'mx0.wwwnew.eu', 'mycard.net.ua',
  'mycleaninbox.net', 'mymail-in.net', 'mypartyclip.de', 'myphantomemail.com',
  'mysamp.de', 'mytempemail.com', 'mytempmail.com', 'mytrashmail.com',
  'nabuma.com', 'neomailbox.com', 'nepwk.com', 'nervmich.net', 'nervtmich.net',
  'netmails.com', 'netmails.net', 'neverbox.com', 'no-spam.ws', 'nobulk.com',
  'noclickemail.com', 'nogmailspam.info', 'nomail.pw', 'nomail.xl.cx',
  'nomail2me.com', 'nomorespamemails.com', 'nospam.ze.tc', 'nospam4.us',
  'nospamfor.us', 'nospamthanks.info', 'notmailinator.com', 'nowmymail.com',
  'nurfuerspam.de', 'nus.edu.sg', 'objectmail.com', 'obobbo.com',
  'odnorazovoe.ru', 'oneoffemail.com', 'onewaymail.com', 'onlatedotcom.info',
  'online.ms', 'opayq.com', 'ordinaryamerican.net', 'otherinbox.com',
  'ovpn.to', 'owlpic.com', 'pancakemail.com', 'pcusers.otherinbox.com',
  'pjjkp.com', 'plexolan.de', 'poofy.org', 'pookmail.com', 'privacy.net',
  'privatdemail.net', 'proxymail.eu', 'prtnx.com', 'punkass.com',
  'putthisinyourspamdatabase.com', 'pwrby.com', 'quickinbox.com',
  'rcpt.at', 'reallymymail.com', 'recode.me', 'recursor.net', 'regbypass.com',
  'regbypass.comsafe-mail.net', 'rmqkr.net', 'royal.net', 'rppkn.com',
  'rtrtr.com', 's0ny.net', 'safe-mail.net', 'safersignup.de', 'safetymail.info',
  'safetypost.de', 'sandelf.de', 'saynotospams.com', 'schafmail.de',
  'selfdestructingmail.com', 'sendspamhere.com', 'sharklasers.com',
  'shieldedmail.com', 'shiftmail.com', 'shitmail.me', 'shortmail.net',
  'sibmail.com', 'sinnlos-mail.de', 'skeefmail.com', 'slaskpost.se',
  'slopsbox.com', 'smashmail.de', 'smellfear.com', 'snakemail.com',
  'sneakemail.com', 'sofimail.com', 'sofort-mail.de', 'sogetthis.com',
  'soodonims.com', 'spam.la', 'spam.su', 'spam4.me', 'spamavert.com',
  'spambob.com', 'spambob.net', 'spambob.org', 'spambog.com', 'spambog.de',
  'spambog.ru', 'spambox.info', 'spambox.us', 'spamcannon.com', 'spamcannon.net',
  'spamcero.com', 'spamcon.org', 'spamcorptastic.com', 'spamcowboy.com',
  'spamcowboy.net', 'spamcowboy.org', 'spamday.com', 'spamex.com',
  'spamfree.eu', 'spamfree24.com', 'spamfree24.de', 'spamfree24.eu',
  'spamfree24.info', 'spamfree24.net', 'spamfree24.org', 'spamgoes.in',
  'spamgourmet.com', 'spamgourmet.net', 'spamgourmet.org', 'spamherelots.com',
  'spamhereplease.com', 'spamhole.com', 'spamify.com', 'spaminator.de',
  'spamkill.info', 'spaml.com', 'spaml.de', 'spammotel.com', 'spamobox.com',
  'spamoff.de', 'spamslicer.com', 'spamspot.com', 'spamthis.co.uk',
  'spamtroll.net', 'speed.1s.fr', 'stuffmail.de', 'super-auswahl.de',
  'supergreatmail.com', 'supermailer.jp', 'superrito.com', 'superstachel.de',
  'suremail.info', 'talkinator.com', 'teewars.org', 'teleworm.com',
  'teleworm.us', 'temp-mail.com', 'temp-mail.org', 'temp-mail.ru', 'tempail.com',
  'tempalias.com', 'tempe-mail.com', 'tempemail.biz', 'tempemail.com',
  'tempemail.net', 'tempinbox.co.uk', 'tempinbox.com', 'tempmail.eu',
  'tempmail.it', 'tempmail2.com', 'tempmaildemo.com', 'tempmailer.com',
  'tempmailer.de', 'tempomail.fr', 'temporarily.de', 'temporarioemail.com.br',
  'temporaryemail.net', 'temporaryforwarding.com', 'temporaryinbox.com',
  'temporarymailaddress.com', 'tempthe.net', 'thanksnospam.info',
  'thankyou2010.com', 'thc.st', 'thelimestones.com', 'thisisnotmyrealemail.com',
  'thismail.net', 'throwam.com', 'throwawayemailaddress.com',
  'throwawaymail.com', 'tilien.com', 'tittbit.in', 'tizi.com', 'tmail.ws',
  'tmailinator.com', 'toomail.biz', 'topranklist.de', 'tradermail.info',
  'trash-amil.com', 'trash-mail.at', 'trash-mail.com', 'trash-mail.de',
  'trash2009.com', 'trashdevil.com', 'trashemail.de', 'trashmail.at',
  'trashmail.com', 'trashmail.de', 'trashmail.me', 'trashmail.net',
  'trashmail.org', 'trashmail.ws', 'trashmailer.com', 'trashymail.com',
  'trashymail.net', 'trialmail.de', 'trillianpro.com', 'twinmail.de',
  'tyldd.com', 'uggsrock.com', 'umail.net', 'upliftnow.com', 'uplipht.com',
  'venompen.com', 'veryrealemail.com', 'viditag.com', 'viewcastmedia.com',
  'viewcastmedia.net', 'viewcastmedia.org', 'walala.org', 'walkmail.net',
  'wasteland.rfc822.org', 'webemail.me', 'weg-werf-email.de', 'wegwerf-emails.de',
  'wegwerfadresse.de', 'wegwerfemail.com', 'wegwerfemail.de', 'wegwerfmail.de',
  'wegwerfmail.info', 'wegwerfmail.net', 'wegwerfmail.org', 'wh4f.org',
  'whyspam.me', 'willhackforfood.biz', 'willselfdestruct.com', 'winemaven.info',
  'wronghead.com', 'wuzup.net', 'wuzupmail.net', 'www.e4ward.com',
  'www.mailinator.com', 'wwwnew.eu', 'xagloo.com', 'xemaps.com',
  'xents.com', 'xmaily.com', 'xoxy.net', 'yep.it', 'yogamaven.com',
  'yopmail.com', 'yopmail.fr', 'yopmail.net', 'ypmail.webarnak.fr.eu.org',
  'yuurok.com', 'zehnminutenmail.de', 'zetmail.com', 'zippymail.in', 'zoaxe.com',
  'zoemail.org', 'zomg.info',
]);

function isDisposableEmailDomain(email) {
  if (!email || typeof email !== 'string') return false;
  const at = email.lastIndexOf('@');
  if (at < 0) return false;
  const domain = email.slice(at + 1).trim().toLowerCase();
  if (!domain) return false;
  return DISPOSABLE_DOMAINS.has(domain);
}

module.exports = { isDisposableEmailDomain, DISPOSABLE_DOMAINS };
